JJFLAGS = -g
JC = javac

.SUFFIXES : .java .class

.java.class:
	$(JC) $(JFLAGS) $*.java
	
CLASSES = \
		SerialvsParallelTest.java

default: classes

classes: $(CLASSES:.java=.class)

clean:
	rm *.class 
